sudo: required

services:
  - docker

install:
  - make build-all

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -y ldap-utils openssl jq

script:
  - make test_1
  - make test_2
  - make test_3
  - make test_4
  - make test_5
  - make test_6
  - make test_7
  - make test_8
